language: python

python:
    - 2.7
    - 3.4
    - 3.5

services:
    - rabbitmq

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install zookeeper
    - export MAJOR_TRAVIS_PYTHON_VERSION=$(python -c "import sys;sys.stdout.write(str(sys.version_info.major))")
    - pip install -r requirements/dev.txt

before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - mkdir -p tmp
    - pushd tmp
    - nosetests --with-lymph lymph
    - popd

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#lymph"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Change view : %{compare_url}"
            - "Build details : %{build_url}"
        use_notice: true
